name: Update Currencies

on:
  
  push:
    branches: [ main ]


  pull_request:
    branches: [ main ]
  

  schedule:
    corn: "0 0 */1 * *" # Every day

  
  workflow_dispatch:


jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.16.1

      - name: Deploy Updated Data
        run: |
          git config --global user.name "TheArmagan"
          git config --global user.email "kiracarmaganonal@gmail.com" 

      - name: Clear API Data
        run: rm -rf ./api

      - name: Clear Old Data
        run: |
          git add api -f
          git commit -m "[🚀] Clear Old Data"
          git push -f
      
      - name: Install Yarn
        run: npm install -g yarn          

      - name: Install Decencies
        run: yarn install --production=true

      - name: Run Updater & Update Data
        run: yarn run data-updater

      - name: Deploy Updated Data
        run: |
          git add api -f
          git commit -m "[🚀] Deploy Updated Data"
          git push -f