name: Update Currencies

on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  
  workflow_dispatch:


jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.16.1
      
      - name: Install Yarn
        run: npm install -g yarn          

      - name: Install Decencies
        run: yarn install --production=true

      - name: Run Updater & Update Data
        run: yarn run data-updater

      - name: Deploy Updated Data
        run: |
          git config user.name ${{ secrets.GH_USER }}
          git config user.email "${{ secrets.GH_MAIL }}"
          git remote add gh-token "https://${{ secrets.GH_TOKEN}}@github.com/:user/:repo.git"

          git add data -f
          git commit -m "Deploy Updated Data"
          git push -f